# Colors (Ayu Dark)
colors:
  # Default colors
  primary:
    background: '#0A0E14'
    foreground: '#B3B1AD'

  # Normal colors
  normal:
    black: '#01060E'
    red: '#EA6C73'
    green: '#91B362'
    yellow: '#F9AF4F'
    blue: '#53BDFA'
    magenta: '#FAE994'
    cyan: '#90E1C6'
    white: '#C7C7C7'

  # Bright colors
  bright:
    black: '#686868'
    red: '#F07178'
    green: '#C2D94C'
    yellow: '#FFB454'
    blue: '#59C2FF'
    magenta: '#FFEE99'
    cyan: '#95E6CB'
    white: '#FFFFFF'
scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 100000
# Background opacity
#
# Window opacity as a floating point number from `0.0` to `1.0`.
# The value `0.0` is completely transparent and `1.0` is opaque.
background_opacity: 0.7

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true
font:
        size: 10.0

key_bindings:
  - { key: V,        mods: Control,    action: Paste               }
  - { key: C,        mods: Control,    action: Copy                }
